window.top.config = {
	Middler:{
		'VESH.view':{
			package:'VJ.view',
			method:'constructor',
			mode:'instance',
			page:{type:'.Page'}
		},
		Ni:{
			package:'VJ.ni',
			constructorparalength:false,size:50,app:'33',
			method:'constructor',
			mode:'static',
			test1:{type:'test',params:[4,{self:true}]},
			test:{type:'test',method:'bean',params:[{params:'Item','a':1,b:2,c:3,d:{type:'test',method:'constructor',params:[4,{self1:true}]}}]},
			ajaxresource:{type:'.NiAjaxDataFactory'},
			objresource:{type:'.NiObjectDataFactory'},
			sqlitefactory:{type:'.NiSqliteDataFactory'},
			cm:{type:'VJ.config.getApplicationConfigManagerFromObj',params:[window.top.ni],method:'factory'},
			template3:{type:'.NiTemplate',mode:'instance',params:[
				{type:'.NiPoolDataResource',params:[{ref:'ajaxresource'},{dbtype:'tjson',jsonp:'_bk'}]},
				{ref:'cm'}
			]},
			template2:{type:'.NiTemplateDecorator',mode:'instance',params:[
				{type:'.NiStaticDataResource',params:[{ref:'ajaxresource'},{dbtype:'tjson',jsonp:'_bk'}]},
				{type:'.NiStaticDataResource',params:[{ref:'objresource'},{resource:window.sessionStorage}]},
				{ref:'cm'},
				{timeout:{interval:'s',number:50}}
			]},	
			template1:{type:'.NiTemplate',mode:'instance',params:[
				{type:'.NiPoolDataResource',params:[{ref:'ajaxresource'},{dbtype:'tjson',jsonp:'_bk'}]},
				{ref:'cm'}
			]},				
			template:{type:'.NiMultiTemplateDecorator',mode:'instance',params:[
				{type:'.NiStaticDataResource',params:[{ref:'ajaxresource'},{dbtype:'tjson',jsonp:'_bk'}]},
				{ref:'cm'},
				{self:true},
				'Ni'
			]},
			sqltemp:{type:'.NiTemplateDecorator',mode:'instance',params:[
				{type:'.NiStaticDataResource',params:[{ref:'sqlitefactory'},{name:'baibings',version:'1.0',desc:'baibings',size:2*1024*1024}]},
				{type:'.NiStaticDataResource',params:[{ref:'objresource'},{resource:window.sessionStorage}]},
				{ref:'cm'},
				{timeout:{interval:'s',number:50}}
			]}
		}
	}
};